import enum
from network.CVAE.src.ReciMePreprocessor import ReciMePreprocessor
from network.CVAE.src.test.expectedEncoding import expectedOutput
import pandas as pd
import numpy as np

def test_decoding():
    preProcessor = ReciMePreprocessor("network/CVAE/data/vocab.bin", "network/CVAE/data/ingredients_unitDict.pkl")

    # Input df + ds
    df = pd.DataFrame(
        data=[
            [8.0, "", "tomatoes"],
            [1, "", "kosher salt"],
            [1.0, "", "red onion"],
            [1.0, "", "green bell pepper"],
            [1.0, "", "red bell pepper"],
            [1.0, "", "yellow bell pepper"],
            [0.5, "", "cucumber"],
            [1, "", "olive oil"],
            [3.0, "", "fresh basil"],
        ],
        columns=["amount", "unit", "ingredient"],
    )
    ds = pd.Series([df], name="ingredients")

    # Expected output
    expectedOutput_amount = [0.0] * 20
    expectedOutput_amount[:len(df['amount'])] = df['amount']

    expectedOutput_unit = [""] * 20
    expectedOutput_unit[:len(df['unit'])] = df['unit']

    expectedOutput_ingredient = [""] * 20
    expectedOutput_ingredient[:len(df['ingredient'])] = df['ingredient']

    # Embed the input data
    output = preProcessor.preProcessInput(ds)
    # Normalize the input data
    output = preProcessor.normalizeData(output)

    # Undo the normalization and revert the embedding
    rebuild_input = preProcessor.decodeOutput(np.array(output))

    # Check that the output generated matches with the expection
    np.testing.assert_almost_equal(expectedOutput_amount, rebuild_input[0]['amount'].astype('float').to_list())
    assert (expectedOutput_unit == rebuild_input[0]['unit']).all()
    assert (expectedOutput_ingredient == rebuild_input[0]['ingredient']).all()

def test_preProcess_light():
    preProcessor = ReciMePreprocessor("network/CVAE/data/vocab.bin", "network/CVAE/data/ingredients_unitDict.pkl")

    # Input df + ds
    df1 = pd.DataFrame(
        data=[
            [1.0, "teaspoon", "chicken"],
            [2.0, "tablespoon", "onions"],
            [3.0, "", "chocolate"],
        ],
        columns=["amount", "unit", "ingredient"],
    )
    ds = pd.Series([df1], name="ingredients")
    output = preProcessor.preProcessInput(ds)[0]
    assert 6360 == len(output)
    #np.testing.assert_almost_equal(expectedOutput, output, verbose=True)

def test_preProcess_medium():
    preProcessor = ReciMePreprocessor("network/CVAE/data/vocab.bin", "network/CVAE/data/ingredients_unitDict.pkl")

    df1 = pd.DataFrame(
        data=[
            [1.0, "cup", "elbow macaroni"],
            [1, "", "American cheese"],
            [0.5, "cup", "celery"],
            [1, "", "green peppers"],
            [1, "", "pimentos"],
            [0.5, "cup", "mayonnaise"],
            [1.0, "tablespoon", "vinegar"],
            [0.75, "teaspoon", "salt"],
            [0.5, "teaspoon", "dry dill weed"],
        ],
        columns=["amount", "unit", "ingredient"],
    )
    df2 = pd.DataFrame(
        data=[
            [8.0, "", "tomatoes"],
            [1, "", "kosher salt"],
            [1.0, "", "red onion"],
            [1.0, "", "green bell pepper"],
            [1.0, "", "red bell pepper"],
            [1.0, "", "yellow bell pepper"],
            [0.5, "", "cucumber"],
            [1, "", "olive oil"],
            [3.0, "", "fresh basil"],
        ],
        columns=["amount", "unit", "ingredient"],
    )
    df3 = pd.DataFrame(
        data=[
            [1, "", "milk"],
            [1, "", "water"],
            [14.0, "cup", "butter"],
            [1.0, "", "mashed potatoes"],
            [1.0, "", "whole kernel corn"],
            [1.0, "cup", "cheddar cheese"],
            [1, "", "French - fried onions"],
        ],
        columns=["amount", "unit", "ingredient"],
    )
    df4 = pd.DataFrame(
        data=[
            [1.0, "", "watermelon gelatin"],
            [14.0, "cup", "boiling water"],
            [1, "", "Cool Whip"],
            [2.0, "cup", "seedless watermelon"],
            [1.0, "", "graham cracker crust"],
        ],
        columns=["amount", "unit", "ingredient"],
    )
    df5 = pd.DataFrame(
        data=[
            [12.0, "cup", "shredded coconut"],
            [1.0, "pound-mass", "lean ground beef"],
            [1.5, "tablespoon", "fresh garlic"],
            [1, "", "salt and black pepper"],
            [1.0, "tablespoon", "lemon juice"],
            [1.0, "tablespoon", "soy sauce"],
            [2.0, "tablespoon", "cornstarch"],
            [1.0, "", "pineapple chunks"],
            [1.0, "", "mandarin oranges"],
            [12.0, "cup", "cashew nuts"],
        ],
        columns=["amount", "unit", "ingredient"],
    )
    df6 = pd.DataFrame(
        data=[
            [2.0, "", "chicken thighs"],
            [2.0, "teaspoon", "tea"],
            [1.0, "", "white pepper"],
        ],
        columns=["amount", "unit", "ingredient"],
    )

    ds = pd.Series([df1, df2, df3, df4, df5, df6], name="ingredients")
    preProcessor.preProcessInput(ds)
    pass


def test_preProcess_heavy():
    preProcessor = ReciMePreprocessor("network/CVAE/data/vocab.bin", "network/CVAE/data/ingredients_unitDict.pkl")

    ds = pd.Series(
        [
            pd.DataFrame(
                data=[
                    [1.0, "cup", "elbow macaroni"],
                    [1, "", "American cheese"],
                    [0.5, "cup", "celery"],
                    [1, "", "green peppers"],
                    [1, "", "pimentos"],
                    [0.5, "cup", "mayonnaise"],
                    [1.0, "tablespoon", "vinegar"],
                    [0.75, "teaspoon", "salt"],
                    [0.5, "teaspoon", "dry dill weed"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [8.0, "", "tomatoes"],
                    [1, "", "kosher salt"],
                    [1.0, "", "red onion"],
                    [1.0, "", "green bell pepper"],
                    [1.0, "", "red bell pepper"],
                    [1.0, "", "yellow bell pepper"],
                    [0.5, "", "cucumber"],
                    [1, "", "olive oil"],
                    [3.0, "", "fresh basil"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "milk"],
                    [1, "", "water"],
                    [14.0, "cup", "butter"],
                    [1.0, "", "mashed potatoes"],
                    [1.0, "", "whole kernel corn"],
                    [1.0, "cup", "cheddar cheese"],
                    [1, "", "French - fried onions"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "watermelon gelatin"],
                    [14.0, "cup", "boiling water"],
                    [1, "", "Cool Whip"],
                    [2.0, "cup", "seedless watermelon"],
                    [1.0, "", "graham cracker crust"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [12.0, "cup", "shredded coconut"],
                    [1.0, "pound-mass", "lean ground beef"],
                    [1.5, "tablespoon", "fresh garlic"],
                    [1, "", "salt and black pepper"],
                    [1.0, "tablespoon", "lemon juice"],
                    [1.0, "tablespoon", "soy sauce"],
                    [2.0, "tablespoon", "cornstarch"],
                    [1.0, "", "pineapple chunks"],
                    [1.0, "", "mandarin oranges"],
                    [12.0, "cup", "cashew nuts"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [2.0, "", "chicken thighs"],
                    [2.0, "teaspoon", "tea"],
                    [1.0, "", "white pepper"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [7.0, "cup", "fresh rhubarb"],
                    [7.0, "cup", "frozen rhubarb"],
                    [1, "", "granulated sugar"],
                    [1, "", "strawberry Jell - O gelatin dessert"],
                    [1.0, "", "white cake mix"],
                    [1, "", "water"],
                    [12.0, "cup", "butter"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "non - fat vanilla yogurt"],
                    [1.0, "cup", "strawberries"],
                    [1, "", "low - fat granola"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [2.0, "cup", "flour"],
                    [1.0, "tablespoon", "cinnamon"],
                    [2.0, "teaspoon", "baking soda"],
                    [1.0, "teaspoon", "salt"],
                    [14.0, "teaspoon", "baking powder"],
                    [3.0, "", "eggs"],
                    [2.0, "cup", "sugar"],
                    [1.0, "cup", "vegetable oil"],
                    [1.0, "tablespoon", "vanilla"],
                    [2.0, "cup", "raw zucchini"],
                    [1.0, "cup", "walnuts"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "teaspoon", "fennel seeds"],
                    [1.0, "pound-mass", "pork tenderloin"],
                    [2.0, "", "fennel bulbs"],
                    [2.0, "tablespoon", "olive oil"],
                    [3.0, "", "garlic cloves"],
                    [0.25, "cup", "dry white wine"],
                    [1, "", "reduced - sodium chicken broth"],
                    [2.0, "tablespoon", "unsalted butter"],
                    [0.5, "teaspoon", "fresh lemon juice"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "rose wine"],
                    [14.0, "cup", "brandy"],
                    [14.0, "cup", "orange liqueur"],
                    [2.0, "cup", "white cranberry juice"],
                    [14.0, "cup", "orange"],
                    [1.0, "", "lemon"],
                    [1, "", "Sprite"],
                    [1, "", "ice cubes"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [14.0, "cup", "butter"],
                    [34.0, "cup", "brown sugar"],
                    [1.0, "", "egg"],
                    [13.0, "cup", "orange juice concentrate"],
                    [1.0, "tablespoon", "orange rind"],
                    [2.0, "cup", "flour"],
                    [1.0, "teaspoon", "baking soda"],
                    [12.0, "teaspoon", "salt"],
                    [1, "", "crushed pineapple in juice"],
                    [12.0, "cup", "pecans"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "ground beef"],
                    [34.0, "cup", "oats"],
                    [12.0, "cup", "tomato juice"],
                    [1.0, "", "egg"],
                    [2.0, "teaspoon", "salt"],
                    [14.0, "teaspoon", "pepper"],
                    [1.0, "teaspoon", "chili powder"],
                    [2.0, "teaspoon", "onions"],
                    [3.0, "tablespoon", "butter"],
                    [3.0, "tablespoon", "flour"],
                    [2.0, "cup", "milk"],
                    [1.0, "cup", "cheddar cheese"],
                    [1, "", "Mexican - style corn"],
                    [2.0, "", "green peppers"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "frozen chopped broccoli"],
                    [1.0, "cup", "cooked rice"],
                    [1.0, "cup", "shredded cheddar cheese"],
                    [1.0, "cup", "shredded cheddar cheese"],
                    [2.0, "", "eggs"],
                    [2.0, "tablespoon", "butter"],
                    [13.0, "cup", "milk"],
                    [1.0, "", "onion"],
                    [1.0, "teaspoon", "garlic powder"],
                    [1.0, "teaspoon", "basil"],
                    [1.0, "teaspoon", "oregano"],
                    [1, "", "salt and pepper"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "cup", "lentils"],
                    [1, "", "onions"],
                    [1.0, "", "tomatoes"],
                    [2.0, "", "carrots"],
                    [2.0, "", "celery"],
                    [3.0, "tablespoon", "extra virgin olive oil"],
                    [1.0, "teaspoon", "garlic powder"],
                    [1.0, "teaspoon", "fresh ginger root juice"],
                    [4.0, "cup", "vegetable broth"],
                    [12.0, "teaspoon", "white pepper"],
                    [12.0, "teaspoon", "chili powder"],
                    [3.0, "cup", "water"],
                    [1, "", "salt and black pepper"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "soymilk"],
                    [1.0, "cup", "frozen blueberries"],
                    [1.0, "cup", "rolled oats"],
                    [0.5, "cup", "sweetened flaked coconut"],
                    [0.5, "cup", "pecans"],
                    [1.0, "cup", "vanilla yogurt"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "vanilla wafer cookie"],
                    [1, "", "bananas"],
                    [2.0, "cup", "coconut milk"],
                    [1, "", "fat - free half - and - half"],
                    [1.0, "tablespoon", "vanilla extract"],
                    [0.5, "teaspoon", "stevia"],
                    [1.0, "cup", "ice cubes"],
                    [4.0, "tablespoon", "whipped cream"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [32.0, "", "graham wafers"],
                    [4.0, "cup", "vanilla ice cream"],
                    [0.75, "cup", "frozen lemonade concentrate"],
                    [1.0, "cup", "chocolate chips"],
                    [0.25, "cup", "butter"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "cinnamon - swirl bread"],
                    [1.0, "", "cream cheese"],
                    [1, "", "apples"],
                    [8.0, "", "eggs"],
                    [1, "", "half - and - half"],
                    [8.0, "tablespoon", "butter"],
                    [14.0, "cup", "maple syrup"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "crabmeat"],
                    [1.0, "", "sour cream"],
                    [1.0, "", "whipped cream cheese"],
                    [1.0, "", "cheese"],
                    [1.0, "", "bacon bits"],
                    [1, "", "cilantro"],
                    [1, "", "cajun seasoning"],
                    [1, "", "garlic powder"],
                    [1, "", "onion powder"],
                    [1, "", "pepper"],
                    [1, "", "salt"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "sweet Italian sausage"],
                    [1.0, "", "mozzarella cheese"],
                    [14.0, "teaspoon", "italian seasoning"],
                    [14.0, "teaspoon", "garlic salt"],
                    [0.5, "", "spaghetti sauce"],
                    [14.0, "teaspoon", "olive oil"],
                    [1.0, "pound-mass", "pizza dough"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [2.0, "", "leeks"],
                    [6.0, "", "smoked bacon"],
                    [1.0, "tablespoon", "unsalted butter"],
                    [3.0, "teaspoon", "kosher salt"],
                    [1, "", "fresh ground black pepper"],
                    [2.0, "", "red potatoes"],
                    [2.0, "", "garlic"],
                    [2.0, "", "fresh thyme"],
                    [6.0, "", "eggs"],
                    [1, "", "half - and - half"],
                    [1, "", "jarlsberg cheese"],
                    [0.5, "teaspoon", "nutmeg"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [3.0, "ounce", "orange juice"],
                    [1.0, "ounce", "white tequila"],
                    [1.0, "ounce", "triple sec"],
                    [1.0, "ounce", "cranberry juice"],
                    [1, "", "orange wedges"],
                    [1, "", "coarse sugar"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "granulated sugar"],
                    [1.0, "", "unsalted butter"],
                    [4.0, "", "egg whites"],
                    [1, "", "lemons, zest of"],
                    [1, "", "lemons, juice of"],
                    [1, "", "all - purpose flour"],
                    [1.0, "teaspoon", "baking powder"],
                    [0.5, "teaspoon", "baking soda"],
                    [1.0, "", "salt"],
                    [0.6666666666666666, "cup", "buttermilk"],
                    [2.0, "cup", "blueberries"],
                    [1.0, "", "granulated sugar"],
                    [1.0, "", "unsalted butter"],
                    [8.0, "ounce", "cream cheese"],
                    [7.0, "", "powdered sugar"],
                    [1.0, "tablespoon", "vanilla extract"],
                    [1.0, "", "salt"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [2.0, "", "avocados"],
                    [1.0, "", "garlic clove"],
                    [4.0, "ounce", "cream cheese"],
                    [1, "", "limes"],
                    [1.0, "tablespoon", "cilantro"],
                    [4.0, "ounce", "sour cream"],
                    [1, "", "fresh jalapenos"],
                    [1, "", "fresh tomatoes"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "nonstick cooking spray"],
                    [1.0, "", "green pepper"],
                    [1.0, "", "red pepper"],
                    [1.0, "", "yellow pepper"],
                    [1.0, "", "red onion"],
                    [1, "", "garlic cloves"],
                    [1, "", "eggplants"],
                    [1, "", "jalapeno peppers"],
                    [1, "", "cilantro leaves"],
                    [1.0, "tablespoon", "capers"],
                    [1, "", "dried currants"],
                    [1.0, "tablespoon", "pine nuts"],
                    [1.0, "tablespoon", "red wine vinegar"],
                    [1.0, "teaspoon", "morton lite salt"],
                    [1, "", "fresh ground black pepper"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "hot banana pepper"],
                    [2.0, "cup", "yellow tomatoes"],
                    [1.0, "", "yellow pepper"],
                    [3.0, "", "scallions"],
                    [3.0, "", "cucumbers"],
                    [2.0, "tablespoon", "fresh basil"],
                    [1.0, "tablespoon", "tarragon"],
                    [1.0, "cup", "vegetable stock"],
                    [12.0, "teaspoon", "salt"],
                    [12.0, "teaspoon", "white pepper"],
                    [1, "", "Worcestershire sauce"],
                    [1, "", "hot sauce"],
                    [1.0, "tablespoon", "sherry wine vinegar"],
                    [14.0, "cup", "vodka"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [2.0, "", "lobster tails"],
                    [1, "", "butter"],
                    [1, "", "lemon juice"],
                    [1, "", "garlic salt"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "egg white"],
                    [18.0, "teaspoon", "salt"],
                    [1.0, "cup", "brown sugar"],
                    [1, "", "all - purpose flour"],
                    [18.0, "teaspoon", "cinnamon"],
                    [1.0, "teaspoon", "vanilla extract"],
                    [1, "", "pecans"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [2.0, "", "wheat flour"],
                    [0.5, "cup", "rolled oats"],
                    [1.0, "tablespoon", "brown sugar"],
                    [2.0, "tablespoon", "dried parsley"],
                    [1.0, "", "apple"],
                    [2.0, "", "carrots"],
                    [1.0, "", "egg"],
                    [0.3333333333333333, "cup", "vegetable oil"],
                    [0.25, "", "water"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "onion"],
                    [3.0, "tablespoon", "oil"],
                    [1.0, "cup", "ketchup"],
                    [12.0, "cup", "water"],
                    [12.0, "cup", "cider vinegar"],
                    [1, "", "sugar"],
                    [1, "", "Worcestershire sauce"],
                    [2.0, "tablespoon", "honey"],
                    [2.0, "teaspoon", "mustard powder"],
                    [2.0, "teaspoon", "paprika"],
                    [1.0, "teaspoon", "salt"],
                    [1, "", "pepper"],
                    [18.0, "teaspoon", "hot pepper sauce"],
                    [1.0, "", "lemon"],
                    [1, "", "hot dogs"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [0.5, "cup", "sugar"],
                    [1.0, "tablespoon", "pumpkin pie spice"],
                    [2.0, "teaspoon", "ground cinnamon"],
                    [1.0, "", "refrigerated biscuits"],
                    [1.0, "", "egg"],
                    [1.0, "tablespoon", "water"],
                    [1.0, "cup", "powdered sugar"],
                    [0.25, "cup", "maple syrup"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [2.0, "tablespoon", "fresh chives"],
                    [6.0, "", "russet potatoes"],
                    [2.0, "", "garlic cloves"],
                    [1.0, "tablespoon", "butter"],
                    [12.0, "cup", "milk"],
                    [12.0, "cup", "sour cream"],
                    [2.0, "tablespoon", "parmesan cheese"],
                    [14.0, "teaspoon", "salt"],
                    [34.0, "teaspoon", "onion salt"],
                    [12.0, "teaspoon", "garlic powder"],
                    [14.0, "teaspoon", "pepper"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "all - purpose flour"],
                    [2.0, "teaspoon", "baking powder"],
                    [1.0, "teaspoon", "baking soda"],
                    [0.5, "teaspoon", "salt"],
                    [0.5, "teaspoon", "ground cinnamon"],
                    [0.25, "teaspoon", "ground ginger"],
                    [0.75, "cup", "brown sugar"],
                    [0.5, "cup", "butter"],
                    [2.0, "", "bananas"],
                    [2.0, "", "eggs"],
                    [1.0, "tablespoon", "lime juice"],
                    [1.0, "teaspoon", "lime zest"],
                    [0.3333333333333333, "cup", "sweetened flaked coconut"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "pound-mass", "penne rigate"],
                    [0.75, "pound-mass", "sugar snap peas"],
                    [0.6666666666666666, "cup", "heavy cream"],
                    [1.0, "", "smoked trout"],
                    [1.0, "tablespoon", "fresh lemon zest"],
                    [0.25, "cup", "fresh dill"],
                    [0.5, "teaspoon", "salt"],
                    [0.5, "teaspoon", "black pepper"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "cup", "water"],
                    [0.5, "cup", "orange juice"],
                    [1.0, "tablespoon", "sugar"],
                    [1, "", "mixed salad greens"],
                    [50.0, "gram", "dates"],
                    [1.0, "", "cinnamon stick"],
                    [1, "", "cream cheese spread"],
                    [1, "", "reduced - fat milk"],
                    [1.0, "teaspoon", "honey"],
                    [1, "", "sliced almonds"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [0.25, "cup", "butter"],
                    [1.0, "", "egg"],
                    [0.25, "cup", "cheese"],
                    [1.0, "", "cracked pepper"],
                    [1.0, "", "rock salt"],
                    [0.5, "teaspoon", "curry powder"],
                    [1.0, "cup", "plain flour"],
                    [4.0, "", "bacon"],
                    [0.25, "cup", "cheese"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [10.0, "ounce", "fettuccine pasta"],
                    [12.0, "cup", "butter"],
                    [1, "", "garlic cloves"],
                    [1.0, "cup", "heavy cream"],
                    [1.0, "", "egg yolk"],
                    [2.0, "cup", "parmesan cheese"],
                    [2.0, "tablespoon", "dried parsley"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "tablespoon", "cornstarch"],
                    [2.0, "tablespoon", "cold water"],
                    [12.0, "cup", "boiling water"],
                    [1.0, "teaspoon", "lemon juice"],
                    [3.0, "", "egg whites"],
                    [6.0, "tablespoon", "sugar"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "pound-mass", "pumpkin"],
                    [1.0, "", "onion"],
                    [2.0, "", "garlic cloves"],
                    [1.0, "tablespoon", "curry powder"],
                    [1, "", "stock"],
                    [2.0, "", "coconut milk"],
                    [200.0, "gram", "smoked salmon"],
                    [1, "", "salt and pepper"],
                    [1, "", "vegetable oil"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [3.0, "", "apples"],
                    [1.0, "cup", "almonds"],
                    [1.0, "cup", "almonds"],
                    [1.0, "", "egg"],
                    [0.5, "cup", "sugar"],
                    [50.0, "gram", "butter"],
                    [2.0, "", "puff pastry"],
                    [1.0, "", "egg"],
                    [1.0, "cup", "almonds"],
                    [0.5, "cup", "sugar"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "all - purpose flour"],
                    [1.0, "teaspoon", "ground cinnamon"],
                    [0.75, "teaspoon", "baking powder"],
                    [0.25, "teaspoon", "baking soda"],
                    [0.25, "teaspoon", "salt"],
                    [0.25, "teaspoon", "ground nutmeg"],
                    [0.3333333333333333, "cup", "margarine"],
                    [0.75, "cup", "dark brown sugar"],
                    [1.0, "", "egg"],
                    [1.0, "teaspoon", "vanilla extract"],
                    [1, "", "rome apples"],
                    [0.75, "cup", "oats"],
                    [0.5, "cup", "dried currants"],
                    [1, "", "cooking spray"],
                    [1.0, "tablespoon", "powdered sugar"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [6.0, "cup", "sushi rice"],
                    [1, "", "Hass avocadoes"],
                    [1, "", "salt"],
                    [1, "", "cucumbers"],
                    [2.0, "", "nori"],
                    [2.0, "pound-mass", "striped bass"],
                    [1.0, "", "scallions"],
                    [2.0, "teaspoon", "sesame seeds"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "ground beef"],
                    [1.0, "", "egg"],
                    [1, "", "low - fat milk"],
                    [1, "", "fine breadcrumbs"],
                    [1, "", "onions"],
                    [0.5, "teaspoon", "salt"],
                    [0.25, "teaspoon", "dry mustard"],
                    [1, "", "pepper"],
                    [2.0, "tablespoon", "flour"],
                    [0.25, "cup", "oil"],
                    [1.0, "", "mushroom soup"],
                    [1, "", "low - fat milk"],
                    [1.0, "", "mixed vegetables"],
                    [0.5, "teaspoon", "salt"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "all - purpose flour"],
                    [1.0, "tablespoon", "white sugar"],
                    [0.5, "teaspoon", "salt"],
                    [0.5, "cup", "vegetable oil"],
                    [2.0, "tablespoon", "milk"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "package", "chocolate cake mix"],
                    [1, "", "Oreo cookies"],
                    [1, "", "instant vanilla pudding"],
                    [1.0, "cup", "milk"],
                    [0.25, "cup", "icing sugar"],
                    [1, "", "Cool Whip Topping"],
                    [1, "", "semi - sweet chocolate chips"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "butternut squash"],
                    [1.0, "", "onion"],
                    [1.0, "tablespoon", "olive oil"],
                    [1.0, "", "apple"],
                    [48.0, "ounce", "chicken broth"],
                    [1, "", "half - and - half"],
                    [2.0, "tablespoon", "parsley"],
                    [1.0, "tablespoon", "thyme"],
                    [1, "", "croutons"],
                    [1, "", "sour cream"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "pound-mass", "turkey"],
                    [1, "", "Italian dressing"],
                    [2.0, "cup", "frozen mixed vegetables"],
                    [1.0, "", "condensed cream of chicken soup"],
                    [1, "", "Velveeta cheese"],
                    [1.0, "", "frozen puff pastry"],
                    [1.0, "", "egg"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "whole wheat flour"],
                    [3.0, "teaspoon", "baking powder"],
                    [14.0, "cup", "extra virgin olive oil"],
                    [2.0, "", "eggs"],
                    [1.0, "cup", "skim milk"],
                    [14.0, "teaspoon", "salt"],
                    [14.0, "teaspoon", "cinnamon"],
                    [14.0, "teaspoon", "nutmeg"],
                    [14.0, "teaspoon", "ground cloves"],
                    [14.0, "teaspoon", "ginger"],
                    [14.0, "teaspoon", "vanilla"],
                    [1, "", "flax seeds"],
                    [3.0, "tablespoon", "honey"],
                    [1, "", "blueberries"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "pound-mass", "corned beef"],
                    [1.0, "cup", "shredded cheddar cheese"],
                    [2.0, "tablespoon", "dried onion flakes"],
                    [1.0, "tablespoon", "dill"],
                    [23.0, "cup", "mayonnaise"],
                    [6.0, "", "hamburger buns"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [0.25, "cup", "heavy cream"],
                    [0.5, "", "lemon curd"],
                    [1.0, "", "cream cheese"],
                    [1, "", "phyllo dough"],
                    [1, "", "fruit slices"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [2.0, "tablespoon", "olive oil"],
                    [2.0, "", "shallots"],
                    [1.0, "teaspoon", "fresh ginger"],
                    [1, "", "tart green apples"],
                    [0.5, "cup", "zucchini"],
                    [1, "", "red bell peppers"],
                    [1, "", "green bell peppers"],
                    [1, "", "carrots"],
                    [0.5, "pound-mass", "crabmeat"],
                    [0.25, "cup", "mayonnaise"],
                    [2.0, "tablespoon", "fresh chives"],
                    [2.0, "", "tomatoes"],
                    [0.3333333333333333, "cup", "fresh cilantro"],
                    [2.0, "tablespoon", "sherry wine vinegar"],
                    [1.0, "", "garlic clove"],
                    [1, "", "cayenne pepper"],
                    [2.0, "tablespoon", "olive oil"],
                    [1, "", "Belgian endive"],
                    [2.0, "tablespoon", "fresh chives"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "all - purpose flour"],
                    [1, "", "Crisco"],
                    [1.0, "ounce", "yeast"],
                    [1.0, "teaspoon", "sugar"],
                    [1.0, "tablespoon", "salt"],
                    [2.0, "tablespoon", "anise seed"],
                    [2.0, "", "eggs"],
                    [1.0, "cup", "water"],
                    [1.0, "tablespoon", "vegetable oil"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "semi - sweet chocolate chips"],
                    [1.0, "tablespoon", "water"],
                    [1.0, "tablespoon", "rum"],
                    [1.0, "tablespoon", "vanilla extract"],
                    [1.0, "", "powdered sugar"],
                    [1.0, "", "ground walnuts"],
                    [1.0, "", "sugar"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "all - purpose flour"],
                    [0.25, "cup", "sugar"],
                    [0.5, "tablespoon", "baking powder"],
                    [0.25, "cup", "unsalted butter"],
                    [1.0, "", "egg"],
                    [0.5, "cup", "ricotta cheese"],
                    [1.0, "teaspoon", "vanilla"],
                    [2.0, "teaspoon", "cinnamon"],
                    [2.0, "", "peaches"],
                    [1.0, "tablespoon", "turbinado sugar"],
                    [1, "", "confectioners' sugar"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[[13.0, "cup", "milk"], [2.0, "teaspoon", "cinnamon"]],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "all - purpose flour"],
                    [0.5, "cup", "walnuts"],
                    [0.25, "cup", "brown sugar"],
                    [0.5, "cup", "butter"],
                    [2.0, "", "strawberries"],
                    [0.5, "cup", "white sugar"],
                    [1.0, "tablespoon", "lemon juice"],
                    [1.0, "", "frozen whipped topping"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [34.0, "cup", "peanut butter"],
                    [12.0, "cup", "sugar"],
                    [1.0, "teaspoon", "vanilla"],
                    [12.0, "teaspoon", "salt"],
                    [1, "", "milk"],
                    [1, "", "whole wheat flour"],
                    [4.0, "teaspoon", "baking powder"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [0.5, "cup", "granulated sugar"],
                    [0.75, "cup", "corn oil"],
                    [1, "", "Egg Beaters egg substitute"],
                    [1.0, "teaspoon", "orange rind"],
                    [0.25, "teaspoon", "orange juice"],
                    [1.0, "tablespoon", "baking powder"],
                    [3.0, "", "flour"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "cantaloupe"],
                    [12.0, "cup", "apple juice"],
                    [1, "", "lime juice"],
                    [1, "", "of fresh mint"],
                    [12.0, "cup", "plain yogurt"],
                    [1.0, "tablespoon", "honey"],
                    [1.0, "pinch", "salt"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [3.0, "cup", "cooked brown rice"],
                    [1.0, "pound-mass", "ground turkey"],
                    [1.0, "", "onion"],
                    [1.0, "", "green bell pepper"],
                    [1.0, "", "pitted black olives"],
                    [12.0, "cup", "raisins"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [12.0, "", "sweet melon"],
                    [2.0, "", "bananas"],
                    [2.0, "", "guavas"],
                    [1.0, "", "grapes"],
                    [1.0, "", "apple"],
                    [2.0, "tablespoon", "orange juice"],
                    [1, "", "pomegranates"],
                    [1.0, "cup", "fresh cream"],
                    [12.0, "teaspoon", "black pepper"],
                    [1.0, "teaspoon", "sugar"],
                    [1, "", "fresh mint leaves"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "wheat berries"],
                    [8.0, "cup", "water"],
                    [14.0, "cup", "almonds"],
                    [14.0, "cup", "pine nuts"],
                    [3.0, "tablespoon", "vegetable oil"],
                    [1.0, "", "onion"],
                    [2.0, "", "minced garlic cloves"],
                    [1.0, "tablespoon", "mild curry paste"],
                    [14.0, "teaspoon", "salt"],
                    [3.0, "tablespoon", "white wine vinegar"],
                    [1.0, "", "red pepper"],
                    [12.0, "cup", "mozzarella cheese"],
                    [2.0, "tablespoon", "parsley"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "old fashioned oats"],
                    [1.0, "cup", "flour"],
                    [12.0, "cup", "brown sugar"],
                    [1.0, "teaspoon", "cinnamon"],
                    [12.0, "teaspoon", "baking soda"],
                    [14.0, "teaspoon", "salt"],
                    [1.0, "cup", "orange juice"],
                    [14.0, "cup", "vegetable oil"],
                    [1.0, "", "egg"],
                    [1.0, "teaspoon", "vanilla"],
                    [6.0, "ounce", "dried mixed fruit"],
                    [1, "", "old fashioned oats"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "popped corn"],
                    [1.0, "cup", "butter"],
                    [2.0, "cup", "brown sugar"],
                    [0.5, "cup", "light corn syrup"],
                    [0.5, "teaspoon", "baking soda"],
                    [0.5, "teaspoon", "vanilla"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "mangoes"],
                    [4.0, "teaspoon", "garlic"],
                    [1, "", "salt"],
                    [3.0, "tablespoon", "chili powder"],
                    [2.0, "tablespoon", "cumin powder"],
                    [1.0, "tablespoon", "coriander"],
                    [3.0, "tablespoon", "masala"],
                    [1, "", "honey"],
                    [12.0, "cup", "cornflour"],
                    [2.0, "tablespoon", "mustard seeds"],
                    [1, "", "curry leaves"],
                    [1, "", "olive oil"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [10.0, "pound-mass", "potatoes"],
                    [2.0, "", "onions"],
                    [9.5, "", "eggs"],
                    [1, "", "salt"],
                    [14.0, "cup", "oil"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "frozen chopped spinach"],
                    [1.0, "cup", "dry breadcrumbs"],
                    [1.0, "", "onion"],
                    [2.0, "", "eggs"],
                    [14.0, "cup", "romano cheese"],
                    [2.0, "teaspoon", "dried oregano"],
                    [1, "", "garlic powder"],
                    [12.0, "teaspoon", "salt"],
                    [1, "", "all purpose Greek seasoning"],
                    [2.0, "pound-mass", "ground lamb"],
                    [1, "", "tzatziki"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [3.0, "pound-mass", "chicken wings"],
                    [1.0, "teaspoon", "salt"],
                    [0.5, "teaspoon", "pepper"],
                    [1.0, "tablespoon", "oil"],
                    [3.0, "tablespoon", "butter"],
                    [0.25, "cup", "hot sauce"],
                    [2.0, "tablespoon", "honey"],
                    [1.0, "tablespoon", "rice wine"],
                    [1.0, "teaspoon", "soy sauce"],
                    [1.0, "teaspoon", "hoisin sauce"],
                    [1.0, "teaspoon", "salt"],
                    [2.0, "tablespoon", "cilantro"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "cup", "slivered almonds"],
                    [2.0, "tablespoon", "light brown sugar"],
                    [2.0, "tablespoon", "butter"],
                    [2.0, "tablespoon", "butter"],
                    [3.0, "ounce", "white chocolate"],
                    [2.0, "", "eggs"],
                    [2.0, "tablespoon", "light brown sugar"],
                    [0.5, "cup", "granulated sugar"],
                    [1, "", "baking powder"],
                    [2.0, "", "lemon peel"],
                    [0.5, "teaspoon", "vanilla"],
                    [0.25, "teaspoon", "almond extract"],
                    [1.0, "", "flour"],
                    [1.0, "cup", "slivered almonds"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [2.0, "", "eggs"],
                    [1, "", "salt"],
                    [1, "", "black pepper"],
                    [2.0, "", "cheese"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "corn kernels"],
                    [1, "", "mushrooms"],
                    [3.0, "", "onions"],
                    [4.0, "", "tomatoes"],
                    [1, "", "red chili peppers"],
                    [1, "", "coriander powder"],
                    [6.0, "", "cloves"],
                    [1.0, "", "bay leaf"],
                    [2.0, "", "star anise"],
                    [1, "", "black pepper"],
                    [1, "", "cornflour"],
                    [1, "", "milk"],
                    [1, "", "fresh cream"],
                    [1, "", "coriander leaves"],
                    [1.0, "tablespoon", "oil"],
                    [1, "", "salt"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [2.0, "tablespoon", "extra virgin olive oil"],
                    [1.0, "", "onion"],
                    [1.0, "", "jalapeno"],
                    [4.0, "", "garlic cloves"],
                    [6.0, "", "red bell peppers"],
                    [1.0, "tablespoon", "red wine vinegar"],
                    [1.0, "tablespoon", "balsamic vinegar"],
                    [1.0, "tablespoon", "light brown sugar"],
                    [1.0, "teaspoon", "ground cumin"],
                    [1, "", "salt"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [2.0, "pound-mass", "shrimp"],
                    [0.75, "cup", "green onions"],
                    [1.0, "", "celery"],
                    [3.0, "tablespoon", "capers"],
                    [1.0, "cup", "black olives"],
                    [1, "", "oil - and - vinegar dressing"],
                    [0.75, "cup", "mayonnaise"],
                    [1, "", "celery seeds"],
                    [1.0, "", "lemon juice"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [34.0, "cup", "creamy peanut butter"],
                    [1, "", "Crisco shortening"],
                    [1, "", "light brown sugar"],
                    [3.0, "tablespoon", "milk"],
                    [1.0, "tablespoon", "vanilla"],
                    [1.0, "", "egg"],
                    [1, "", "flour"],
                    [34.0, "teaspoon", "salt"],
                    [34.0, "teaspoon", "baking soda"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [3.0, "", "chicken sausage"],
                    [1.0, "", "garlic clove"],
                    [1.0, "", "onion"],
                    [1.0, "", "green pepper"],
                    [2.0, "", "carrots"],
                    [3.0, "tablespoon", "soy sauce"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "pound-mass", "bacon"],
                    [5.0, "", "garlic cloves"],
                    [2.0, "", "fresh mushrooms"],
                    [2.0, "tablespoon", "extra virgin olive oil"],
                    [4.0, "tablespoon", "butter"],
                    [1, "", "Campbell's Cream of Mushroom Soup"],
                    [0.0, "", "milk"],
                    [14.0, "teaspoon", "black pepper"],
                    [1, "", "frozen French - cut green beans"],
                    [1, "", "French's French fried onions"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "egg"],
                    [18.0, "cup", "water"],
                    [1, "", "all - purpose flour"],
                    [2.0, "teaspoon", "fine sea salt"],
                    [1.0, "teaspoon", "ground black pepper"],
                    [1, "", "vegetable oil"],
                    [1.0, "", "cauliflower"],
                    [4.0, "ounce", "green beans"],
                    [1.0, "", "fennel bulb"],
                    [1.0, "cup", "garbanzo beans"],
                    [1.0, "", "lemon"],
                    [1.0, "cup", "mayonnaise"],
                    [2.0, "tablespoon", "fresh lemon juice"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.5, "", "acorn squash"],
                    [15.0, "ounce", "black beans"],
                    [15.0, "ounce", "crushed tomatoes"],
                    [2.0, "", "onions"],
                    [4.0, "", "garlic cloves"],
                    [1.0, "quart", "vegetable broth"],
                    [1.0, "tablespoon", "olive oil"],
                    [1.0, "tablespoon", "cumin"],
                    [1, "", "salt and pepper"],
                    [1.0, "", "avocado"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "cherry pie filling"],
                    [1.0, "", "dark sweet cherries"],
                    [23.0, "cup", "quick oats"],
                    [1, "", "Bisquick baking mix"],
                    [12.0, "cup", "brown sugar"],
                    [14.0, "cup", "nuts"],
                    [14.0, "cup", "butter"],
                    [1.0, "teaspoon", "cinnamon"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [4.0, "cup", "watermelon"],
                    [1, "", "lime - flavored seltzer water"],
                    [1, "", "Splenda sugar substitute"],
                    [1, "", "lemons"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [12.0, "cup", "cocoa powder"],
                    [12.0, "cup", "honey"],
                    [1, "", "natural - style peanut butter"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "graham cracker crumb crust"],
                    [0.5, "cup", "seedless raspberry preserves"],
                    [1, "", "Philadelphia Cream Cheese"],
                    [0.5, "cup", "creamy peanut butter"],
                    [0.75, "cup", "brown sugar"],
                    [1, "", "Cool Whip Topping"],
                    [0.25, "cup", "dry roasted peanuts"],
                    [1, "", "raspberries"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "cup", "mashed potatoes"],
                    [1.0, "cup", "flour"],
                    [1.0, "", "fresh parsley"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "process American cheese"],
                    [13.0, "cup", "milk"],
                    [14.0, "teaspoon", "onion salt"],
                    [1.0, "drop", "red pepper sauce"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [0.25, "cup", "brown sugar"],
                    [1, "", "chili powder"],
                    [1.0, "tablespoon", "paprika"],
                    [1, "", "spareribs"],
                    [8.0, "ounce", "tomato sauce"],
                    [0.25, "cup", "vinegar"],
                    [1.0, "tablespoon", "salt and pepper"],
                    [1, "", "celery seeds"],
                    [1, "", "lemons"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "breakfast sausage"],
                    [1.0, "", "flour tortilla"],
                    [1.0, "tablespoon", "cream cheese"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [8.0, "ounce", "unsweetened chocolate"],
                    [1.0, "", "unsalted butter"],
                    [1.0, "cup", "sugar"],
                    [0.75, "cup", "dark brown sugar"],
                    [1, "", "all - purpose flour"],
                    [13.0, "cup", "unsweetened cocoa powder"],
                    [0.5, "teaspoon", "baking soda"],
                    [0.5, "teaspoon", "kosher salt"],
                    [4.0, "", "eggs"],
                    [1, "", "powdered sugar"],
                    [4.0, "tablespoon", "smooth peanut butter"],
                    [1.0, "", "real vanilla extract"],
                    [4.0, "tablespoon", "whole milk"],
                    [1, "", "chocolate sprinkles"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [3.0, "ounce", "unsweetened chocolate"],
                    [3.0, "ounce", "cream cheese"],
                    [1, "", "low - fat milk"],
                    [4.0, "cup", "confectioners' sugar"],
                    [0.5, "teaspoon", "salt"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "lemon Jell - O gelatin"],
                    [1.0, "", "crushed pineapple"],
                    [1.0, "", "fruit cocktail"],
                    [1.0, "cup", "cottage cheese"],
                    [1.0, "", "evaporated milk"],
                    [12.0, "cup", "mayonnaise"],
                    [12.0, "cup", "pecans"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "all - purpose flour"],
                    [14.0, "teaspoon", "lemon pepper seasoning"],
                    [2.0, "tablespoon", "butter"],
                    [2.0, "tablespoon", "heavy cream"],
                    [1.0, "cup", "swiss cheese"],
                    [1.0, "", "boneless pork loin roast"],
                    [6.0, "ounce", "deli ham"],
                    [1.0, "teaspoon", "paprika"],
                    [12.0, "teaspoon", "dried marjoram"],
                    [12.0, "teaspoon", "dried oregano"],
                    [12.0, "teaspoon", "dried basil"],
                    [1.0, "", "onion"],
                    [2.0, "tablespoon", "butter"],
                    [1.0, "tablespoon", "cornstarch"],
                    [1.0, "cup", "heavy whipping cream"],
                    [14.0, "cup", "chicken broth"],
                    [1.0, "teaspoon", "sour cream"],
                    [1, "", "salt"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "stone - ground yellow cornmeal"],
                    [1, "", "all - purpose flour"],
                    [0.75, "cup", "pumpkin seeds"],
                    [2.0, "teaspoon", "kosher salt"],
                    [2.0, "teaspoon", "sugar"],
                    [1, "", "crushed red pepper flakes"],
                    [6.0, "tablespoon", "unsalted butter"],
                    [3.0, "tablespoon", "milk"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "brown sugar"],
                    [12.0, "cup", "canola oil"],
                    [1.0, "", "egg"],
                    [2.0, "teaspoon", "vanilla"],
                    [1.0, "cup", "buttermilk"],
                    [1, "", "flour"],
                    [1.0, "teaspoon", "baking soda"],
                    [12.0, "teaspoon", "salt"],
                    [1.0, "tablespoon", "baking powder"],
                    [1, "", "rhubarb"],
                    [1, "", "nuts"],
                    [1.0, "cup", "butter"],
                    [1, "", "sugar"],
                    [1.0, "teaspoon", "cinnamon"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [2.0, "pound-mass", "onions"],
                    [1.0, "tablespoon", "margarine"],
                    [1.0, "tablespoon", "sugar"],
                    [1, "", "salt and pepper"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "chicken wings"],
                    [1.0, "", "cilantro"],
                    [1, "", "garlic clove"],
                    [1.0, "", "jalapeno"],
                    [2.0, "tablespoon", "fish sauce"],
                    [2.0, "tablespoon", "fresh lime juice"],
                    [6.0, "tablespoon", "unsalted butter"],
                    [1.0, "cup", "flour"],
                    [1.0, "", "canola oil"],
                    [1.0, "", "kosher salt"],
                    [1.0, "", "black pepper"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1, "", "milk chocolate candy bars"],
                    [1.0, "", "milk"],
                    [1, "", "Greek yogurt"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "pound-mass", "ground beef"],
                    [1, "", "onions"],
                    [1, "", "Hunts tomato sauce"],
                    [1.0, "", "diced tomatoes"],
                    [2.0, "cup", "water"],
                    [1.0, "cup", "pasta"],
                    [1.0, "", "kidney beans"],
                    [1, "", "Kraft Grated Parmesan Cheese"],
                    [1.0, "tablespoon", "chili powder"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [10.0, "", "whole wheat tortillas"],
                    [1, "", "diced tomatoes with green pepper and onion"],
                    [1, "", "black olives"],
                    [2.0, "cup", "monterey jack cheese"],
                    [4.0, "", "chicken thighs"],
                    [1, "", "olive oil"],
                    [1, "", "green taco sauce"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [2.0, "tablespoon", "gochujang"],
                    [1, "", "persimmons"],
                    [2.0, "tablespoon", "sugar"],
                    [1.0, "tablespoon", "raspberry extract"],
                    [1.0, "teaspoon", "soy sauce"],
                    [1, "", "udon noodles"],
                    [1, "", "English cucumber"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
            pd.DataFrame(
                data=[
                    [1.0, "", "pizza sauce"],
                    [2.0, "teaspoon", "italian seasoning"],
                    [1.0, "teaspoon", "garlic powder"],
                    [14.0, "cup", "pepperoni"],
                    [1, "", "green peppers"],
                    [1.0, "pinch", "red pepper flakes"],
                    [12.0, "cup", "mozzarella cheese"],
                    [12.0, "", "garlic bread"],
                ],
                columns=["amount", "unit", "ingredient"],
            ),
        ],
        name='ingredients'
    )

    preProcessor.preProcessInput(ds)
    pass